# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krateo < Formula
  desc "Cross OS commandline tool to manage Krateo Platform."
  homepage "https://github.com/krateoplatformops/homebrew-krateo"
  version "0.4.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krateoplatformops/krateo/releases/download/v0.4.3/krateo_0.4.3_darwin_amd64.tar.gz"
      sha256 "ccb9ffae95fa706c44caa4c0e5e4a4a5c2dffe951fb172ae315a18a3d7dbbc71"

      def install
        bin.install "krateo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/krateoplatformops/krateo/releases/download/v0.4.3/krateo_0.4.3_linux_amd64.tar.gz"
      sha256 "f45c2047794d4743acf4088d6744a8a91042ebca2baa18b236b9df532f3edb8d"

      def install
        bin.install "krateo"
      end
    end
  end
end
