# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krateo < Formula
  desc "Cross OS commandline tool to manage Krateo Platform."
  homepage "https://github.com/krateoplatformops/homebrew-krateo"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krateoplatformops/krateo/releases/download/v1.1.0/krateo_1.1.0_darwin_arm64.tar.gz"
      sha256 "654e241c8d5657353d41770e68d934e65dae2fab0b39433ae410dce09baf2a67"

      def install
        bin.install "krateo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krateoplatformops/krateo/releases/download/v1.1.0/krateo_1.1.0_darwin_amd64.tar.gz"
      sha256 "8afb89c247c678af7f318567674f4a5792bea852ccff55803499b2c87def7b9a"

      def install
        bin.install "krateo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krateoplatformops/krateo/releases/download/v1.1.0/krateo_1.1.0_linux_arm64.tar.gz"
      sha256 "fce5775111815dbce9a1d3001600c360a2c4b81ccacb535f8a5c6530beefeafc"

      def install
        bin.install "krateo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krateoplatformops/krateo/releases/download/v1.1.0/krateo_1.1.0_linux_amd64.tar.gz"
      sha256 "c1b76d7c5ff53377c8029f67ad0a805167530b046255f178f29c00d840caddbc"

      def install
        bin.install "krateo"
      end
    end
  end
end
