# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krateo < Formula
  desc "Cross OS commandline tool to manage Krateo Platform."
  homepage "https://github.com/krateoplatformops/homebrew-krateo"
  version "0.4.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krateoplatformops/krateo/releases/download/v0.4.11/krateo_0.4.11_darwin_amd64.tar.gz"
      sha256 "3269b412d025acfe3d69981d63d7d219feece55510db5e2e5a8998b2e4f6410d"

      def install
        bin.install "krateo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/krateoplatformops/krateo/releases/download/v0.4.11/krateo_0.4.11_linux_amd64.tar.gz"
      sha256 "d4e9fef582b37dff4d9eebb2d48d95615c11ac3389e63b7aaf34a33f1454494d"

      def install
        bin.install "krateo"
      end
    end
  end
end
